apiVersion: v1
kind: ServiceAccount
metadata:
  name: conformance
  namespace: conformance
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: conformance
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: conformance
    namespace: conformance
---
apiVersion: batch/v1
kind: Job
metadata:
  name: conformance
  namespace: conformance
spec:
  template:
    metadata:
      labels:
        app: conformance
    spec:
      serviceAccount: conformance
      containers:
        - name: conformance
          image: replace-img
      restartPolicy: Never
  backoffLimit: 0